### ISSUE TITLE
Blue Skin for the Face in Input Image while using runvx.

### ISSUE THREAD

**Issue by lcskrishna** [GPUOpen-ProfessionalCompute-Libraries/amdovx-core#13]
Hello,
While I am experimenting with the amdovx-core, I tried to run the code for skintonedetect.gdf which is given in the ReadMe.md in runvx folder.
After the code has been executed , I am able to see the input window with the following image rather than the given input image (http://cdn5.applesencia.com/wp-content/blogs.dir/17/files/2013/04/raja-koduri-640x480.jpg) :

![inputimage_blueskin](https://cloud.githubusercontent.com/assets/6920620/21361021/4325d7ce-c6b0-11e6-9b43-9f6b6ea4eb45.png)

**Comment by rgiduthuri** [comment]
Hi Chaitanya, Thanks for reporting the problem. 
The runvx tool is currently using OpenCV library for the reading the images which uses BGR layout for the image data buffer and OpenVX expects data in RGB order. That's why the current version of skintonedetect.gdf uses channels IDs in reverse order for channel_extract nodes.
I will get this fixed in next commit since this can be very confusing.

**Comment by lcskrishna** [comment]
Hello,
I tried to check with the updated GDF and the latest source code and am not able to see that issue again. 

Thanks,
Chaitanya.
